import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Momtan Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const rubik = Rubik({
  subsets: ["latin", "arabic"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className} antialiased bg-white`}>
        {children}
      </body>
    </html>
  );
}
